decoupled_preview_iframe.settings:
  type: config_object
  label: 'Decoupled preview iframe settings'
  mapping:
    route_sync:
      type: string
      label: 'Route syncing'
    draft_provider:
      type: string
      label: 'Draft provider'
    preview_url:
      type: uri
      label: 'Preview URL'
    preview_types:
      type: sequence
      label: 'Preview pages'
      sequence:
        type: preview_type.[%key]
        label: 'Entity type'

preview_type.*:
  type: sequence
  sequence:
    type: string
    label: 'Bundle type'
